export const STRIPE_SECRET = process.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY!;

export const APPWRITE_ENDPOINT = process.env.NEXT_PUBLIC_APPWRITE_ENDPOINT!;

export const APPWRITE_PROJECT_ID = process.env.NEXT_PUBLIC_APPWRITE_PROJECT_ID!;

export const APPWRITE_BUCKET = process.env.NEXT_PUBLIC_APPWRITE_BUCKET!;


export const GOOGLE_CLIENT_ID = process.env.GOOGLE_CLIENT_ID!;
export const GOOGLE_CLIENT_SECRET = process.env.GOOGLE_CLIENT_SECRET!;

export const NEXT_AUTH_SECRET = process.env.NEXT_AUTH_SECRET!;
